# Generated by Django 5.2.7 on 2025-10-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.IntegerField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('RETIRADA', 'Retirada'), ('DEVOLUCAO', 'Devolução'), ('ATUALIZACAO', 'Atualizacao')], max_length=20)),
                ('horario', models.DateTimeField()),
                ('id_chave', models.ForeignKey(db_column='Id_chave', on_delete=django.db.models.deletion.PROTECT, to='guarita.chave')),
                ('id_pessoa', models.ForeignKey(db_column='Id_pessoa', on_delete=django.db.models.deletion.PROTECT, to='guarita.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='ChaveStatus',
            fields=[
                ('id_chave', models.OneToOneField(db_column='Id_chave', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='guarita.chave')),
                ('checkin', models.DateTimeField()),
                ('status_code', models.BooleanField()),
                ('id_pessoa', models.ForeignKey(db_column='Id_pessoa', on_delete=django.db.models.deletion.PROTECT, to='guarita.pessoa')),
            ],
            options={
                'unique_together': {('id_pessoa', 'id_chave')},
            },
        ),
    ]
