# Generated by Django 5.2.7 on 2025-10-30 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chavestatus',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chavestatus',
            name='id_pessoa',
            field=models.ForeignKey(blank=True, db_column='Id_pessoa', null=True, on_delete=django.db.models.deletion.PROTECT, to='guarita.pessoa'),
        ),
        migrations.AlterField(
            model_name='chavestatus',
            name='status_code',
            field=models.BooleanField(editable=False),
        ),
    ]
