# Generated by Django 5.2.7 on 2025-11-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0002_alter_chavestatus_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='itemBusca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='itemBusca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
