# Generated by Django 5.2.7 on 2025-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0003_chave_itembusca_pessoa_itembusca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='id_chave',
            new_name='chave',
        ),
        migrations.RenameField(
            model_name='historico',
            old_name='id_pessoa',
            new_name='pessoa',
        ),
        migrations.AlterField(
            model_name='historico',
            name='id_historico',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
