# Generated by Django 5.2.7 on 2025-11-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0004_rename_id_chave_historico_chave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chavestatus',
            old_name='id_chave',
            new_name='chave',
        ),
        migrations.RenameField(
            model_name='chavestatus',
            old_name='id_pessoa',
            new_name='pessoa',
        ),
        migrations.AlterUniqueTogether(
            name='chavestatus',
            unique_together={('pessoa', 'chave')},
        ),
    ]
