# Generated by Django 5.2.7 on 2025-11-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0005_rename_id_chave_chavestatus_chave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='id_historico',
            field=models.BigAutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
