# Generated by Django 5.2.7 on 2025-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0006_alter_historico_id_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='id_historico',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
