# Generated by Django 5.2.8 on 2025-11-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0007_alter_historico_id_historico'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chavestatus',
            unique_together=set(),
        ),
    ]
