# Generated by Django 5.2.8 on 2025-12-05 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0008_alter_chavestatus_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='itemBusca',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL),
        ),
    ]
