# Generated by Django 5.2.8 on 2025-12-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0009_remove_pessoa_cargo_remove_pessoa_itembusca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='guarita.chave')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='guarita.pessoa')),
            ],
            options={
                'verbose_name': 'Permissao de Chave',
                'verbose_name_plural': 'Permissões de Chaves',
                'unique_together': {('pessoa', 'chave')},
            },
        ),
    ]
