# Generated by Django 5.2.8 on 2026-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0010_restricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
