# Generated by Django 5.2.8 on 2026-01-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0011_alter_pessoa_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
