# Generated by Django 5.2.8 on 2026-03-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarita', '0012_pessoa_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chavestatus',
            name='chave',
            field=models.OneToOneField(db_column='Id_chave', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guarita.chave'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='chave',
            field=models.ForeignKey(db_column='Id_chave', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guarita.chave'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='pessoa',
            field=models.ForeignKey(db_column='Id_pessoa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='guarita.pessoa'),
        ),
    ]
